version: '2'

services:

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./frontend:/code
  #   ports:
  #     - 3000:3000
  #   # environment:
  #   #   - NODE_PATH=/install/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/code
    ports:
      - 8000:80
    environment:
      - DJANGO_SETTINGS_MODULE=dev_settings
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate && uwsgi --ini uwsgi.ini'
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80'
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80'
